.PHONY: clean All

All:
	@echo "----------Building project:[ 06_Variables_and_constants - Debug ]----------"
	@cd "Project2" && "$(MAKE)" -f  "06_Variables_and_constants.mk"
clean:
	@echo "----------Cleaning project:[ 06_Variables_and_constants - Debug ]----------"
	@cd "Project2" && "$(MAKE)" -f  "06_Variables_and_constants.mk" clean
