.PHONY: clean All

All:
	@echo "----------Building project:[ 06.48_What_is_the_Size_of_a_Variable - Debug ]----------"
	@cd "06.48_What_is_the_Size_of_a_Variable" && "$(MAKE)" -f  "06.48_What_is_the_Size_of_a_Variable.mk"
clean:
	@echo "----------Cleaning project:[ 06.48_What_is_the_Size_of_a_Variable - Debug ]----------"
	@cd "06.48_What_is_the_Size_of_a_Variable" && "$(MAKE)" -f  "06.48_What_is_the_Size_of_a_Variable.mk" clean
